branch: master
tagFormat: '${version}'

verifyConditions:
  - path: &npm '@semantic-release/npm'
    pkgRoot: '.'
  - &gh '@semantic-release/github'

prepare:
  - '@semantic-release/changelog'
  - '@alorel-personal/semantic-release'
  - *npm
  - path: &exec '@semantic-release/exec'
    cmd: doctoc --github README.md
  - path: *exec
    cmd: node ./postprocess.js
  - path: *exec
    cmd: alo copy-files
  - path: *exec
    cmd: alo clean-dist
  - path: *exec
    cmd: alo clean-pkg-json
  - path: '@semantic-release/git'
    message: 'chore(release): ${nextRelease.version}'
    assets:
      - CHANGELOG.md
      - README.md
      - package.json
      - yarn.lock
      - projects/ngx-auto-id/package.json
  - path: *exec
    cmd: ./mkrelease.sh

publish:
  - path: *exec
    cmd: npm publish ./dist.tgz
  - *gh

generateNotes:
  config: '@alorel-personal/conventional-changelog-alorel'
